@baseUrl = https://simplepokeapi-json.onrender.com

### Root
GET {{baseUrl}}/
Accept: application/json

### List pokemons
# @name listPokemons
GET {{baseUrl}}/api/pokemons
Accept: application/json

### Create pokemon
# @name createPokemon
POST {{baseUrl}}/api/pokemons
Content-Type: application/json

{
  "name": "Pikachu HTTP",
  "type": "Electric",
  "imageUrl": "https://img.pokemondb.net/artwork/pikachu.jpg"
}

### Get pokemon by id (from create response)
GET {{baseUrl}}/api/pokemons/{{createPokemon.response.body.$.id}}
Accept: application/json

### Update pokemon by id
PATCH {{baseUrl}}/api/pokemons/{{createPokemon.response.body.$.id}}
Content-Type: application/json

{
  "type": "Electric/Test"
}

### Delete pokemon by id
DELETE {{baseUrl}}/api/pokemons/{{createPokemon.response.body.$.id}}

### Verify delete (should be 404)
GET {{baseUrl}}/api/pokemons/{{createPokemon.response.body.$.id}}
Accept: application/json
