services:
  - type: web
    name: simplepokeapi-json
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: corepack enable && corepack prepare yarn@1.22.22 --activate && yarn install --frozen-lockfile && yarn run build
    startCommand: yarn run start
    envVars:
      - key: NODE_VERSION
        value: 22
